# Elastic Beanstalk Nginx Configuration File for Staging

user                    nginx;
error_log               /var/log/nginx/error.log warn;
pid                     /var/run/nginx.pid;
worker_processes        auto;
worker_rlimit_nofile    32650;

events {
    worker_connections  1024;
}

http {
    client_max_body_size        1024M;

    # Testing Proxy Config
    proxy_cache_path /tmp/nginx_cache
    keys_zone=my_cache:100m max_size=100m inactive=60m use_temp_path=off;
    # End test

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    include       conf.d/*.conf;

    server_tokens off;

    map $http_upgrade $connection_upgrade {
        default     "upgrade";
    }

    server {
        listen        80 default_server;
        server_name   _;  # Catch-all server name to respond to any domain

        access_log    /var/log/nginx/access.log main;

        client_header_timeout 60;
        client_body_timeout   60;
        keepalive_timeout     60;
        gzip                  on;
        gzip_comp_level       4;
        gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        # Include the Elastic Beanstalk generated locations
        include conf.d/elasticbeanstalk/*.conf;

        # Additions from Laravel deployment docs
        add_header X-Frame-Options "SAMEORIGIN";

        # Security headers
        add_header X-Content-Type-Options "nosniff" always;
        add_header Content-Security-Policy "frame-ancestors 'self'" always;
        add_header Referrer-Policy "same-origin";

        location / {
           try_files $uri $uri/ /index.php?$query_string;
        }

        # location /testing-cacheable {

        #     proxy_buffering on;

        #     proxy_pass http://localhost/;  # Adjust the backend URL if needed

        #     proxy_pass_request_headers on;

        #     # Enable caching with the in-memory cache zone
        #     proxy_cache my_cache;

        #     # Cache key definition
        #     proxy_cache_key "$scheme$request_method$host$request_uri";

        #     # Cache settings
        #     proxy_cache_valid 200 302 10m;
        #     proxy_cache_valid 404 1m;
        #     proxy_cache_use_stale error timeout updating;

        #     # Pass headers
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #     proxy_set_header X-Forwarded-Proto $scheme;

        #     # Add header to indicate cache status
        #     add_header X-Cache-Status $upstream_cache_status;
        # }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        error_page 404 /index.php;

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}
